Generate_Model = False
NumberOfNeurons = 185
Training_Epochs = 15
Checkpoint_Path ="Image_Classification/Model_Training/checkpoint.ckpt"
Show_Input_Images = False
Evaluate_Model = True
Model_Name = 'NN_Model.keras'
Execute_Predictions = True
Number_Shown_Predictions = 10
Prediction_Index_Start = 400